/* GENERATED by scripts/google-ads/build-search-terms.py from content/campaigns/google-ads/search-terms/2026-09-30-terms.json. Do not edit. */
window.TERMS = {
 "account": "Credo Legal (9399506772)",
 "period": "LAST_30_DAYS as of 2026-09-30 (2026-08-31 to 2026-09-29)",
 "source": "Google Ads API v24 via Ryze connector, search_term_view (read-only GAQL)",
 "threshold": "S_All-States and S_Lawsuit_NW: terms with >=15 impressions (S_Lawsuit_NW misses its 16 lowest-volume terms at that cut, API page limit); S_Garnishment_NW, S_CreditCard_NW, S_Harassment_NW, S_Brand: >=20 impressions",
 "rows": [
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment immediately online",
   "impr": 593,
   "clicks": 72,
   "cost": 460.93,
   "conv": 10.33,
   "top": 0.886
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment",
   "impr": 560,
   "clicks": 34,
   "cost": 240.16,
   "conv": 3.67,
   "top": 0.566
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop a wage garnishment immediately",
   "impr": 555,
   "clicks": 62,
   "cost": 388.45,
   "conv": 2.0,
   "top": 0.875
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection attorney",
   "impr": 499,
   "clicks": 30,
   "cost": 387.16,
   "conv": 1.5,
   "top": 0.8789808917197452,
   "absTop": 0.34076433121019106
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection lawyer",
   "impr": 417,
   "clicks": 38,
   "cost": 505.22,
   "conv": 6.83,
   "top": 0.8932806324110671,
   "absTop": 0.308300395256917
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "debt collection defense attorney near me",
   "impr": 391,
   "clicks": 24,
   "cost": 257.76,
   "conv": 5.5,
   "top": 0.879245283018868,
   "absTop": 0.3660377358490566
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyer",
   "impr": 361,
   "clicks": 22,
   "cost": 368.2,
   "conv": 10.67,
   "top": 0.8991596638655462,
   "absTop": 0.2815126050420168
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishment",
   "impr": 339,
   "clicks": 10,
   "cost": 70.67,
   "conv": 1.0,
   "top": 0.627
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to get a debt lawsuit dismissed",
   "impr": 325,
   "clicks": 31,
   "cost": 171.69,
   "conv": 3.25,
   "top": 0.875,
   "absTop": 0.28879310344827586
  },
  {
   "campaign": "S_Brand",
   "adgroup": "Brand_Core",
   "term": "credo legal",
   "impr": 286,
   "clicks": 71,
   "cost": 199.7,
   "conv": 10.47,
   "top": 0.7934272300469484,
   "absTop": 0.6431924882629108
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment lawyer",
   "impr": 284,
   "clicks": 34,
   "cost": 391.17,
   "conv": 1.0,
   "top": 0.865
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment",
   "impr": 269,
   "clicks": 62,
   "cost": 388.91,
   "conv": 4.0,
   "top": 0.95
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment",
   "impr": 267,
   "clicks": 46,
   "cost": 302.11,
   "conv": 5.01,
   "top": 0.888
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt attorney near me",
   "impr": 263,
   "clicks": 23,
   "cost": 316.4,
   "conv": 5.01,
   "top": 0.8674698795180723,
   "absTop": 0.3253012048192771
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawyer near me",
   "impr": 252,
   "clicks": 37,
   "cost": 550.54,
   "conv": 7.5,
   "top": 0.8947368421052632,
   "absTop": 0.4152046783625731
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collector lawyer",
   "impr": 236,
   "clicks": 17,
   "cost": 173.43,
   "conv": 1.0,
   "top": 0.8431372549019608,
   "absTop": 0.20915032679738563
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishment lawyer",
   "impr": 215,
   "clicks": 29,
   "cost": 305.2,
   "conv": 5.0,
   "top": 0.858
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "creditor garnishment",
   "impr": 212,
   "clicks": 11,
   "cost": 82.98,
   "conv": 2.0,
   "top": 0.734
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "consumer debt attorney near me",
   "impr": 209,
   "clicks": 14,
   "cost": 244.08,
   "conv": 0.0,
   "top": 0.8770491803278688,
   "absTop": 0.4098360655737705
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment",
   "impr": 205,
   "clicks": 55,
   "cost": 376.68,
   "conv": 5.0,
   "top": 0.957
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "consumer debt attorney",
   "impr": 204,
   "clicks": 14,
   "cost": 215.7,
   "conv": 2.0,
   "top": 0.808,
   "absTop": 0.312
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt attorney",
   "impr": 204,
   "clicks": 8,
   "cost": 97.86,
   "conv": 1.0,
   "top": 0.9166666666666666,
   "absTop": 0.30303030303030304
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment immediately online",
   "impr": 201,
   "clicks": 23,
   "cost": 132.85,
   "conv": 1.0,
   "top": 0.867
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyer near me",
   "impr": 190,
   "clicks": 11,
   "cost": 145.46,
   "conv": 1.5,
   "top": 0.8611111111111112,
   "absTop": 0.2777777777777778
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense attorney near me",
   "impr": 189,
   "clicks": 18,
   "cost": 208.75,
   "conv": 4.5,
   "top": 0.7846153846153846,
   "absTop": 0.3769230769230769
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "what happens if a debt collector sues you and you have no money",
   "impr": 175,
   "clicks": 10,
   "cost": 69.6,
   "conv": 0.0,
   "top": 0.8661417322834646,
   "absTop": 0.2047244094488189
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense attorney",
   "impr": 171,
   "clicks": 14,
   "cost": 251.65,
   "conv": 7.0,
   "top": 0.8376068376068376,
   "absTop": 0.6068376068376068
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Creditor_Suing",
   "term": "midland credit management lawsuit",
   "impr": 161,
   "clicks": 5,
   "cost": 28.78,
   "conv": 1.0,
   "top": 0.38848920863309355,
   "absTop": 0.06474820143884892
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment attorney near me",
   "impr": 160,
   "clicks": 21,
   "cost": 246.77,
   "conv": 3.0,
   "top": 0.804
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt settlement attorney",
   "impr": 157,
   "clicks": 9,
   "cost": 187.84,
   "conv": 1.0,
   "top": 0.9047619047619048,
   "absTop": 0.3142857142857143
  },
  {
   "campaign": "S_Brand",
   "adgroup": "Brand_Core",
   "term": "credo legal services",
   "impr": 151,
   "clicks": 62,
   "cost": 172.85,
   "conv": 5.0,
   "top": 0.9186991869918699,
   "absTop": 0.5365853658536586
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection attorney near me",
   "impr": 148,
   "clicks": 10,
   "cost": 115.24,
   "conv": 0.0,
   "top": 0.8522727272727273,
   "absTop": 0.3977272727272727
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment lawyer near me",
   "impr": 142,
   "clicks": 15,
   "cost": 143.24,
   "conv": 2.0,
   "top": 0.892
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "fdcpa",
   "impr": 138,
   "clicks": 12,
   "cost": 39.76,
   "conv": 0.0,
   "top": 0.4752475247524752,
   "absTop": 0.26732673267326734
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "how to get a credit card lawsuit dismissed",
   "impr": 137,
   "clicks": 9,
   "cost": 41.24,
   "conv": 0.0,
   "top": 0.8571428571428571,
   "absTop": 0.17142857142857143
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment attorney",
   "impr": 134,
   "clicks": 17,
   "cost": 211.04,
   "conv": 10.0,
   "top": 0.869
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishment lawyers near me",
   "impr": 129,
   "clicks": 15,
   "cost": 147.82,
   "conv": 2.0,
   "top": 0.892
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "15 usc 1692",
   "impr": 126,
   "clicks": 10,
   "cost": 41.72,
   "conv": 0.0,
   "top": 0.8229166666666666,
   "absTop": 0.3020833333333333
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop garnishment",
   "impr": 124,
   "clicks": 25,
   "cost": 273.65,
   "conv": 1.5,
   "top": 0.987
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment immediately",
   "impr": 123,
   "clicks": 11,
   "cost": 82.91,
   "conv": 5.0,
   "top": 0.881
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection lawyer near me",
   "impr": 118,
   "clicks": 8,
   "cost": 76.15,
   "conv": 1.0,
   "top": 0.7857142857142857,
   "absTop": 0.4714285714285714
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection lawyers near me",
   "impr": 117,
   "clicks": 8,
   "cost": 121.48,
   "conv": 2.0,
   "top": 0.8450704225352113,
   "absTop": 0.28169014084507044
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyers",
   "impr": 116,
   "clicks": 11,
   "cost": 165.27,
   "conv": 0.0,
   "top": 0.88,
   "absTop": 0.25333333333333335
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collector attorney",
   "impr": 106,
   "clicks": 8,
   "cost": 93.2,
   "conv": 0.0,
   "top": 0.8208955223880597,
   "absTop": 0.31343283582089554
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment from your check",
   "impr": 105,
   "clicks": 18,
   "cost": 129.58,
   "conv": 0.5,
   "top": 0.939
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment",
   "impr": 102,
   "clicks": 13,
   "cost": 49.83,
   "conv": 0.0,
   "top": 0.94
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collections attorney",
   "impr": 99,
   "clicks": 7,
   "cost": 96.63,
   "conv": 2.5,
   "top": 0.78125,
   "absTop": 0.21875
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "lawyer for debt collection",
   "impr": 97,
   "clicks": 13,
   "cost": 157.85,
   "conv": 1.5,
   "top": 0.9166666666666666,
   "absTop": 0.3
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment lawyers near me",
   "impr": 94,
   "clicks": 8,
   "cost": 50.18,
   "conv": 0.0,
   "top": 0.925
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how can i stop a wage garnishment immediately",
   "impr": 90,
   "clicks": 11,
   "cost": 55.56,
   "conv": 2.0,
   "top": 0.946
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment immediately",
   "impr": 87,
   "clicks": 7,
   "cost": 45.16,
   "conv": 1.0,
   "top": 0.9
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop wage garnishment",
   "impr": 87,
   "clicks": 16,
   "cost": 173.34,
   "conv": 4.92,
   "top": 0.906
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "attorney for debt collection",
   "impr": 85,
   "clicks": 9,
   "cost": 99.69,
   "conv": 0.0,
   "top": 0.8909090909090909,
   "absTop": 0.4
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collections lawyer",
   "impr": 85,
   "clicks": 2,
   "cost": 31.84,
   "conv": 0.0,
   "top": 0.8478260869565217,
   "absTop": 0.391304347826087
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "how to get a debt lawsuit dismissed",
   "impr": 84,
   "clicks": 4,
   "cost": 22.5,
   "conv": 0.0,
   "top": 0.813953488372093,
   "absTop": 0.2558139534883721
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishment attorney",
   "impr": 83,
   "clicks": 9,
   "cost": 96.01,
   "conv": 0.0,
   "top": 0.918
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card lawyer",
   "impr": 83,
   "clicks": 2,
   "cost": 18.86,
   "conv": 0.0,
   "top": 0.7966101694915254,
   "absTop": 0.288135593220339
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "attorney for debt collection lawsuit",
   "impr": 82,
   "clicks": 6,
   "cost": 129.97,
   "conv": 0.0,
   "top": 0.8771929824561403,
   "absTop": 0.3157894736842105
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt settlement attorney near me",
   "impr": 81,
   "clicks": 14,
   "cost": 235.85,
   "conv": 4.63,
   "top": 0.8524590163934426,
   "absTop": 0.32786885245901637
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishment lawyers near me",
   "impr": 81,
   "clicks": 16,
   "cost": 205.22,
   "conv": 8.0,
   "top": 0.82
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a wage garnishment",
   "impr": 80,
   "clicks": 9,
   "cost": 43.7,
   "conv": 1.5,
   "top": 0.981
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawyers near me",
   "impr": 77,
   "clicks": 7,
   "cost": 112.09,
   "conv": 0.0,
   "top": 0.8653846153846154,
   "absTop": 0.40384615384615385
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection defense attorney near me",
   "impr": 77,
   "clicks": 4,
   "cost": 35.26,
   "conv": 1.0,
   "top": 0.851063829787234,
   "absTop": 0.2553191489361702
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector lawyer near me",
   "impr": 73,
   "clicks": 17,
   "cost": 209.18,
   "conv": 2.5,
   "top": 0.9574468085106383,
   "absTop": 0.5106382978723404
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Negotiation",
   "term": "pds debt",
   "impr": 72,
   "clicks": 1,
   "cost": 20.73,
   "conv": 1.0,
   "top": 0.5483870967741935,
   "absTop": 0.24193548387096775
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "collections lawyer",
   "impr": 69,
   "clicks": 6,
   "cost": 91.59,
   "conv": 0.0,
   "top": 0.8913043478260869,
   "absTop": 0.45652173913043476
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "im being sued for a debt what do i do",
   "impr": 69,
   "clicks": 9,
   "cost": 61.8,
   "conv": 1.0,
   "top": 0.9215686274509803,
   "absTop": 0.2549019607843137
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collection attorney near me",
   "impr": 68,
   "clicks": 4,
   "cost": 75.66,
   "conv": 4.0,
   "top": 0.6976744186046512,
   "absTop": 0.18604651162790697
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt attorneys near me",
   "impr": 68,
   "clicks": 5,
   "cost": 65.93,
   "conv": 0.5,
   "top": 0.7954545454545454,
   "absTop": 0.2727272727272727
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "fair debt collection practices act",
   "impr": 68,
   "clicks": 5,
   "cost": 20.19,
   "conv": 0.0,
   "top": 0.5319148936170213,
   "absTop": 0.3617021276595745
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to file a motion to stop garnishment",
   "impr": 68,
   "clicks": 7,
   "cost": 48.42,
   "conv": 1.0,
   "top": 0.805
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop wage garnishment immediately",
   "impr": 68,
   "clicks": 6,
   "cost": 54.63,
   "conv": 1.0,
   "top": 0.86
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collection defense attorney",
   "impr": 66,
   "clicks": 11,
   "cost": 159.34,
   "conv": 0.83,
   "top": 0.9473684210526315,
   "absTop": 0.47368421052631576
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Creditor_Suing",
   "term": "lvnv funding llc lawsuit",
   "impr": 66,
   "clicks": 1,
   "cost": 2.44,
   "conv": 0.0,
   "top": 0.6037735849056604,
   "absTop": 0.2830188679245283
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishment attorney near me",
   "impr": 66,
   "clicks": 8,
   "cost": 82.91,
   "conv": 1.0,
   "top": 0.667
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector attorney near me",
   "impr": 65,
   "clicks": 3,
   "cost": 35.87,
   "conv": 0.0,
   "top": 0.875,
   "absTop": 0.375
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "being sued by a debt collector",
   "impr": 64,
   "clicks": 9,
   "cost": 73.7,
   "conv": 0.0,
   "top": 0.9534883720930233,
   "absTop": 0.2558139534883721
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "consumer debt lawyer",
   "impr": 64,
   "clicks": 1,
   "cost": 7.55,
   "conv": 0.0,
   "top": 1,
   "absTop": 0.625
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection lawyers",
   "impr": 64,
   "clicks": 5,
   "cost": 64.88,
   "conv": 1.0,
   "top": 0.85,
   "absTop": 0.3
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnish wages",
   "impr": 64,
   "clicks": 2,
   "cost": 36.21,
   "conv": 0.5,
   "top": 0.75
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card debt lawyer",
   "impr": 64,
   "clicks": 6,
   "cost": 104.15,
   "conv": 1.0,
   "top": 0.8695652173913043,
   "absTop": 0.1956521739130435
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyers near me",
   "impr": 63,
   "clicks": 6,
   "cost": 105.18,
   "conv": 0.0,
   "top": 0.9069767441860465,
   "absTop": 0.20930232558139536
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can you stop a garnishment after it starts",
   "impr": 62,
   "clicks": 10,
   "cost": 54.21,
   "conv": 1.83,
   "top": 0.841
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "collection lawyers",
   "impr": 61,
   "clicks": 6,
   "cost": 79.16,
   "conv": 1.0,
   "top": 0.7727272727272727,
   "absTop": 0.4318181818181818
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishments",
   "impr": 61,
   "clicks": 6,
   "cost": 34.39,
   "conv": 1.0,
   "top": 0.711
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collection attorney",
   "impr": 61,
   "clicks": 2,
   "cost": 26.14,
   "conv": 0.0,
   "top": 0.6829268292682927,
   "absTop": 0.34146341463414637
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collection lawyers near me",
   "impr": 61,
   "clicks": 5,
   "cost": 59.16,
   "conv": 0.0,
   "top": 0.627906976744186,
   "absTop": 0.2558139534883721
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Branded",
   "term": "dnf associates llc",
   "impr": 61,
   "clicks": 4,
   "cost": 28.2,
   "conv": 2.0,
   "top": 0.62,
   "absTop": 0.4
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "15 usc 1692",
   "impr": 60,
   "clicks": 2,
   "cost": 6.03,
   "conv": 0.0,
   "top": 0.7142857142857143,
   "absTop": 0.30952380952380953
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment of wages",
   "impr": 59,
   "clicks": 14,
   "cost": 107.77,
   "conv": 0.0,
   "top": 0.975
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card lawsuit",
   "impr": 56,
   "clicks": 3,
   "cost": 11.43,
   "conv": 0.0,
   "top": 0.95,
   "absTop": 0.2
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment of wages",
   "impr": 55,
   "clicks": 3,
   "cost": 4.96,
   "conv": 0.0,
   "top": 0.609
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishment lawyers",
   "impr": 55,
   "clicks": 5,
   "cost": 74.0,
   "conv": 0.0,
   "top": 0.969
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "wage garnishment california",
   "impr": 55,
   "clicks": 3,
   "cost": 11.31,
   "conv": 0.0,
   "top": 0.718
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card attorney",
   "impr": 55,
   "clicks": 4,
   "cost": 62.75,
   "conv": 0.0,
   "top": 0.7419354838709677,
   "absTop": 0.3225806451612903
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "stop wage garnishment",
   "impr": 54,
   "clicks": 2,
   "cost": 23.75,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collections attorney near me",
   "impr": 54,
   "clicks": 3,
   "cost": 46.4,
   "conv": 1.0,
   "top": 0.7027027027027027,
   "absTop": 0.32432432432432434
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "fdcpa violations",
   "impr": 53,
   "clicks": 7,
   "cost": 17.14,
   "conv": 0.0,
   "top": 0.5526315789473685,
   "absTop": 0.39473684210526316
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishment of wages",
   "impr": 53,
   "clicks": 3,
   "cost": 9.57,
   "conv": 1.0,
   "top": 0.727
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "lawyer for credit card debt",
   "impr": 53,
   "clicks": 4,
   "cost": 27.67,
   "conv": 0.0,
   "top": 0.8918918918918919,
   "absTop": 0.16216216216216217
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "sued by debt collector",
   "impr": 52,
   "clicks": 1,
   "cost": 2.82,
   "conv": 0.0,
   "top": 0.9117647058823529,
   "absTop": 0.17647058823529413
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense lawyer near me",
   "impr": 51,
   "clicks": 6,
   "cost": 133.86,
   "conv": 1.0,
   "top": 0.84375,
   "absTop": 0.53125
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "credit corp solutions inc suing me",
   "impr": 50,
   "clicks": 2,
   "cost": 7.41,
   "conv": 0.0,
   "top": 0.8125,
   "absTop": 0.3125
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to get a debt lawsuit dismissed online",
   "impr": 50,
   "clicks": 9,
   "cost": 45.4,
   "conv": 1.01,
   "top": 0.8857142857142857,
   "absTop": 0.42857142857142855
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop a wage garnishment",
   "impr": 50,
   "clicks": 4,
   "cost": 30.41,
   "conv": 0.0,
   "top": 0.917
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "stop wage garnishment immediately",
   "impr": 49,
   "clicks": 7,
   "cost": 54.75,
   "conv": 2.0,
   "top": 0.969
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "who can garnish wages without notice",
   "impr": 49,
   "clicks": 1,
   "cost": 3.39,
   "conv": 0.0,
   "top": 0.61
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyer for debt collection lawsuit",
   "impr": 48,
   "clicks": 6,
   "cost": 60.05,
   "conv": 2.0,
   "top": 0.9714285714285714,
   "absTop": 0.4
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to get a debt lawsuit dismissed",
   "impr": 48,
   "clicks": 3,
   "cost": 10.17,
   "conv": 0.0,
   "top": 0.8387096774193549,
   "absTop": 0.22580645161290322
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop garnishment immediately",
   "impr": 48,
   "clicks": 9,
   "cost": 102.01,
   "conv": 1.0,
   "top": 0.9
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debtstoppers il",
   "impr": 47,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.9354838709677419,
   "absTop": 0.5483870967741935
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "can you stop a garnishment after it starts",
   "impr": 47,
   "clicks": 1,
   "cost": 2.54,
   "conv": 0.0,
   "top": 0.625
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card debt attorney near me",
   "impr": 47,
   "clicks": 1,
   "cost": 6.68,
   "conv": 0.0,
   "top": 0.7407407407407407,
   "absTop": 0.37037037037037035
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card lawyers near me",
   "impr": 47,
   "clicks": 3,
   "cost": 31.23,
   "conv": 1.0,
   "top": 0.7428571428571429,
   "absTop": 0.3142857142857143
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense law",
   "impr": 46,
   "clicks": 3,
   "cost": 22.02,
   "conv": 1.0,
   "top": 0.6857142857142857,
   "absTop": 0.08571428571428572
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to answer a court summons debt collection",
   "impr": 46,
   "clicks": 2,
   "cost": 13.29,
   "conv": 0.0,
   "top": 0.9,
   "absTop": 0.26666666666666666
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "writ of garnishment",
   "impr": 46,
   "clicks": 1,
   "cost": 3.23,
   "conv": 0.0,
   "top": 0.786
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how do i stop a garnishment",
   "impr": 46,
   "clicks": 7,
   "cost": 38.58,
   "conv": 1.0,
   "top": 1
  },
  {
   "campaign": "S_Brand",
   "adgroup": "Brand_Core",
   "term": "credolegal",
   "impr": 46,
   "clicks": 22,
   "cost": 61.54,
   "conv": 3.5,
   "top": 0.9210526315789473,
   "absTop": 0.5789473684210527
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "best debt collection defense attorney near me",
   "impr": 45,
   "clicks": 2,
   "cost": 15.39,
   "conv": 0.0,
   "top": 0.7586206896551724,
   "absTop": 0.41379310344827586
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "fdcpa violations",
   "impr": 45,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.6571428571428571,
   "absTop": 0.2
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Creditor_Suing",
   "term": "mandarich law group llp",
   "impr": 45,
   "clicks": 2,
   "cost": 42.05,
   "conv": 0.0,
   "top": 0.46153846153846156,
   "absTop": 0.23076923076923078
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment",
   "impr": 45,
   "clicks": 3,
   "cost": 14.18,
   "conv": 0.0,
   "top": 0.828
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Negotiation",
   "term": "credit acceptance settlement offer",
   "impr": 45,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.6666666666666666,
   "absTop": 0.1794871794871795
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "can a debt collector sue you",
   "impr": 44,
   "clicks": 1,
   "cost": 3.39,
   "conv": 0.0,
   "top": 0.6153846153846154,
   "absTop": 0.23076923076923078
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment lawyers",
   "impr": 44,
   "clicks": 4,
   "cost": 47.02,
   "conv": 0.0,
   "top": 0.955
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment from debt collector",
   "impr": 44,
   "clicks": 7,
   "cost": 29.92,
   "conv": 1.0,
   "top": 0.969
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop garnishment of my paycheck online",
   "impr": 43,
   "clicks": 10,
   "cost": 80.76,
   "conv": 0.5,
   "top": 0.931
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "being sued by credit card company",
   "impr": 43,
   "clicks": 1,
   "cost": 4.95,
   "conv": 0.0,
   "top": 0.9166666666666666,
   "absTop": 0.1388888888888889
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "what to do if a debt collector sues you",
   "impr": 42,
   "clicks": 2,
   "cost": 9.18,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment from your check",
   "impr": 42,
   "clicks": 2,
   "cost": 9.85,
   "conv": 0.5,
   "top": 0.955
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyer cost",
   "impr": 41,
   "clicks": 4,
   "cost": 60.86,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense lawyer",
   "impr": 40,
   "clicks": 5,
   "cost": 39.9,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt settlement lawyer",
   "impr": 40,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "consumer debt defense attorney",
   "impr": 39,
   "clicks": 6,
   "cost": 90.63,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collection lawsuit",
   "impr": 39,
   "clicks": 1,
   "cost": 5.54,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "i m being sued by a debt collector",
   "impr": 39,
   "clicks": 4,
   "cost": 44.3,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "klima peters & daly p a",
   "impr": 39,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "being sued for credit card debt",
   "impr": 39,
   "clicks": 3,
   "cost": 36.06,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Branded",
   "term": "resurgent debt collector",
   "impr": 39,
   "clicks": 1,
   "cost": 2.55,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to respond to a summons",
   "impr": 38,
   "clicks": 4,
   "cost": 18.09,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnish wages",
   "impr": 38,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.167
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card lawyers",
   "impr": 38,
   "clicks": 5,
   "cost": 32.94,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Branded",
   "term": "lnvn",
   "impr": 38,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawsuit lawyer near me",
   "impr": 37,
   "clicks": 4,
   "cost": 34.95,
   "conv": 1.33
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment",
   "impr": 37,
   "clicks": 4,
   "cost": 14.16,
   "conv": 0.0,
   "top": 0.909
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection defense attorney",
   "impr": 37,
   "clicks": 3,
   "cost": 28.13,
   "conv": 1.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "lawyers for debt collection",
   "impr": 37,
   "clicks": 1,
   "cost": 20.71,
   "conv": 1.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can you stop a garnishment",
   "impr": 37,
   "clicks": 4,
   "cost": 9.31,
   "conv": 0.0,
   "top": 0.923
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to fight a garnishment",
   "impr": 37,
   "clicks": 4,
   "cost": 47.57,
   "conv": 4.0,
   "top": 0.905
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment of wages",
   "impr": 37,
   "clicks": 8,
   "cost": 54.8,
   "conv": 1.0,
   "top": 0.958
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop garnishment letter",
   "impr": 37,
   "clicks": 6,
   "cost": 41.66,
   "conv": 1.0,
   "top": 0.88
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawsuit attorney",
   "impr": 36,
   "clicks": 3,
   "cost": 35.17,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawsuit lawyer",
   "impr": 36,
   "clicks": 6,
   "cost": 103.62,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to respond to a court summons for debt",
   "impr": 36,
   "clicks": 4,
   "cost": 19.92,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "help with wage garnishment",
   "impr": 36,
   "clicks": 5,
   "cost": 55.42,
   "conv": 1.0,
   "top": 0.905
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to file a motion to stop garnishment",
   "impr": 36,
   "clicks": 4,
   "cost": 12.17,
   "conv": 1.0,
   "top": 0.762
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can you stop wage garnishment after it starts",
   "impr": 36,
   "clicks": 3,
   "cost": 20.16,
   "conv": 1.0,
   "top": 0.833
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishing wages",
   "impr": 36,
   "clicks": 1,
   "cost": 1.56,
   "conv": 0.0,
   "top": 0.484
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment immediately",
   "impr": 36,
   "clicks": 9,
   "cost": 56.59,
   "conv": 0.0,
   "top": 0.84
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "lawyer to stop wage garnishment",
   "impr": 36,
   "clicks": 4,
   "cost": 27.04,
   "conv": 0.0,
   "top": 0.826
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "being sued by debt collector",
   "impr": 35,
   "clicks": 3,
   "cost": 16.52,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "collections lawyer near me",
   "impr": 35,
   "clicks": 4,
   "cost": 41.32,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector suing me",
   "impr": 35,
   "clicks": 2,
   "cost": 33.82,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "fair debt collection practices act",
   "impr": 35,
   "clicks": 1,
   "cost": 14.18,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection defense lawyer",
   "impr": 35,
   "clicks": 1,
   "cost": 7.06,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "loan lawyers",
   "impr": 35,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to find out who garnished my wages",
   "impr": 35,
   "clicks": 3,
   "cost": 24.89,
   "conv": 0.0,
   "top": 0.783
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop a garnishment on my paycheck",
   "impr": 34,
   "clicks": 5,
   "cost": 28.98,
   "conv": 1.5,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop garnishments",
   "impr": 34,
   "clicks": 3,
   "cost": 25.1,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "lawyer for credit card lawsuit",
   "impr": 34,
   "clicks": 2,
   "cost": 23.95,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Negotiation",
   "term": "debt settlement companies",
   "impr": 34,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "klima peters & daly p a",
   "impr": 33,
   "clicks": 1,
   "cost": 12.17,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt lawyer nyc",
   "impr": 33,
   "clicks": 6,
   "cost": 51.18,
   "conv": 2.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can a garnishment be stopped",
   "impr": 33,
   "clicks": 4,
   "cost": 20.56,
   "conv": 3.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishment help",
   "impr": 33,
   "clicks": 8,
   "cost": 72.15,
   "conv": 1.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "wage garnishment florida",
   "impr": 33,
   "clicks": 2,
   "cost": 5.05,
   "conv": 0.0,
   "top": 0.696
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to dispute a debt collection",
   "impr": 32,
   "clicks": 1,
   "cost": 6.42,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyer for debt collection lawsuit near me",
   "impr": 32,
   "clicks": 6,
   "cost": 96.62,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "debt collection lawsuit attorney near me",
   "impr": 32,
   "clicks": 2,
   "cost": 14.6,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to file an answer to a debt lawsuit",
   "impr": 32,
   "clicks": 2,
   "cost": 6.63,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card lawsuit attorney near me",
   "impr": 32,
   "clicks": 1,
   "cost": 10.92,
   "conv": 0.0
  },
  {
   "campaign": "S_Brand",
   "adgroup": "Brand_Core",
   "term": "credo law",
   "impr": 32,
   "clicks": 13,
   "cost": 34.15,
   "conv": 2.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how much does a debt settlement lawyer cost",
   "impr": 31,
   "clicks": 2,
   "cost": 28.59,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "credit garnishment",
   "impr": 31,
   "clicks": 1,
   "cost": 1.42,
   "conv": 0.0,
   "top": 0.8
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt settlement attorney",
   "impr": 31,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawsuit attorney near me",
   "impr": 30,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "gurstel law firm p c",
   "impr": 30,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "what to do if debt is past statute of limitations",
   "impr": 30,
   "clicks": 1,
   "cost": 1.41,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment of wages",
   "impr": 30,
   "clicks": 2,
   "cost": 4.05,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "gurstel law firm p c",
   "impr": 30,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "creditor garnishment on paycheck",
   "impr": 30,
   "clicks": 3,
   "cost": 12.0,
   "conv": 0.0,
   "top": 0.762
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnished wages",
   "impr": 30,
   "clicks": 3,
   "cost": 16.0,
   "conv": 0.0,
   "top": 0.636
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop wage garnishment once it starts",
   "impr": 30,
   "clicks": 7,
   "cost": 54.8,
   "conv": 0.0,
   "top": 0.952
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "what to do if your wages are garnished",
   "impr": 30,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.87
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "can a debt collector take you to court",
   "impr": 29,
   "clicks": 3,
   "cost": 11.31,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "can a debt collector take you to court after 7 years",
   "impr": 29,
   "clicks": 3,
   "cost": 9.33,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "crown asset management lawsuit",
   "impr": 29,
   "clicks": 3,
   "cost": 14.76,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "harrer law",
   "impr": 29,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to dispute a debt and win",
   "impr": 29,
   "clicks": 1,
   "cost": 6.97,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "fair debt collection practices act",
   "impr": 29,
   "clicks": 3,
   "cost": 22.01,
   "conv": 0.0
  },
  {
   "campaign": "S_Harassment_NW",
   "adgroup": "FDCPA_Harassment",
   "term": "fdcpa attorney near me",
   "impr": 29,
   "clicks": 5,
   "cost": 40.56,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "newstart legal",
   "impr": 28,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "can you stop wage garnishment after it starts",
   "impr": 28,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.526
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection attorneys near me",
   "impr": 28,
   "clicks": 1,
   "cost": 12.6,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how do you stop a garnishment",
   "impr": 28,
   "clicks": 5,
   "cost": 25.71,
   "conv": 0.0,
   "top": 0.895
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment in memphis tn",
   "impr": 28,
   "clicks": 3,
   "cost": 30.75,
   "conv": 0.0,
   "top": 0.895
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "can a credit card company sue you",
   "impr": 28,
   "clicks": 2,
   "cost": 5.88,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "capital one is suing me what can i do",
   "impr": 27,
   "clicks": 4,
   "cost": 33.88,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collection defense attorney nyc",
   "impr": 27,
   "clicks": 2,
   "cost": 27.52,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "is it illegal for a collection agency to buy your debt and come after you",
   "impr": 27,
   "clicks": 2,
   "cost": 3.75,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "should i hire an attorney for debt settlement",
   "impr": 27,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment of wages",
   "impr": 27,
   "clicks": 3,
   "cost": 27.97,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt defense attorney near me",
   "impr": 27,
   "clicks": 2,
   "cost": 11.19,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "low cost debt attorney",
   "impr": 27,
   "clicks": 1,
   "cost": 29.62,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "tromberg miller morris & partners pllc",
   "impr": 27,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop a garnishment",
   "impr": 27,
   "clicks": 6,
   "cost": 56.06,
   "conv": 1.0,
   "top": 0.955
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to find out whos garnishing your wages",
   "impr": 27,
   "clicks": 1,
   "cost": 5.22,
   "conv": 0.0,
   "top": 0.895
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card attorney near me",
   "impr": 27,
   "clicks": 3,
   "cost": 15.42,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "lawyers for credit card lawsuit",
   "impr": 27,
   "clicks": 5,
   "cost": 61.99,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense attorney cost",
   "impr": 26,
   "clicks": 1,
   "cost": 19.17,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Creditor_Suing",
   "term": "midland credit management suing me",
   "impr": 26,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "claim of exemption",
   "impr": 26,
   "clicks": 1,
   "cost": 2.08,
   "conv": 0.0,
   "top": 0.647
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how can i stop a garnishment on my paycheck",
   "impr": 26,
   "clicks": 5,
   "cost": 23.56,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collector lawyer near me",
   "impr": 26,
   "clicks": 1,
   "cost": 12.13,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "15 usc 1692",
   "impr": 26,
   "clicks": 3,
   "cost": 5.84,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop garnishment of my paycheck",
   "impr": 26,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.941
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how do i stop a garnishment on paycheck",
   "impr": 26,
   "clicks": 3,
   "cost": 5.6,
   "conv": 0.0,
   "top": 0.895
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to file an exemption for wage garnishment",
   "impr": 26,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "stop a garnishment",
   "impr": 26,
   "clicks": 5,
   "cost": 48.72,
   "conv": 1.67,
   "top": 0.938
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collections attorney",
   "impr": 25,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt defense",
   "impr": 25,
   "clicks": 1,
   "cost": 8.09,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawyer nyc",
   "impr": 25,
   "clicks": 2,
   "cost": 46.62,
   "conv": 0.4
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "jefferson capital systems suing me",
   "impr": 25,
   "clicks": 2,
   "cost": 10.18,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "what to do when a debt collector sues you",
   "impr": 25,
   "clicks": 2,
   "cost": 8.77,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to respond to a summons from a debt collector",
   "impr": 25,
   "clicks": 2,
   "cost": 10.74,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can i stop a garnishment",
   "impr": 25,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to avoid wage garnishment",
   "impr": 25,
   "clicks": 2,
   "cost": 16.99,
   "conv": 0.0,
   "top": 0.9
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "lawyer for garnishment",
   "impr": 25,
   "clicks": 2,
   "cost": 51.89,
   "conv": 0.0,
   "top": 0.857
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "can debt collectors sue you",
   "impr": 24,
   "clicks": 2,
   "cost": 7.15,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collection attorneys",
   "impr": 24,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt lawsuit defense attorney near me",
   "impr": 24,
   "clicks": 3,
   "cost": 63.7,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "what happens if a debt collector sues you and you have no money",
   "impr": 24,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishing wages",
   "impr": 24,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.533
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "lawyer for garnished wages",
   "impr": 24,
   "clicks": 1,
   "cost": 10.05,
   "conv": 0.0,
   "top": 0.8
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "lawyer to stop wage garnishment",
   "impr": 24,
   "clicks": 4,
   "cost": 32.7,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collector harassment",
   "impr": 24,
   "clicks": 5,
   "cost": 34.08,
   "conv": 2.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "can a debt collector garnish your wages",
   "impr": 24,
   "clicks": 2,
   "cost": 11.29,
   "conv": 0.39,
   "top": 0.75
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how do i stop garnishment of my wages",
   "impr": 24,
   "clicks": 7,
   "cost": 62.55,
   "conv": 0.0,
   "top": 0.938
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop wage garnishment in florida",
   "impr": 24,
   "clicks": 5,
   "cost": 43.42,
   "conv": 1.03,
   "top": 1
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lvnv suing me",
   "impr": 23,
   "clicks": 2,
   "cost": 14.7,
   "conv": 1.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "can you stop a garnishment",
   "impr": 23,
   "clicks": 1,
   "cost": 5.58,
   "conv": 0.0,
   "top": 0.727
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collection lawyers",
   "impr": 23,
   "clicks": 3,
   "cost": 37.25,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to file a claim of exemption wage garnishment",
   "impr": 23,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.8
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to get a garnishment lowered",
   "impr": 23,
   "clicks": 5,
   "cost": 25.45,
   "conv": 0.0,
   "top": 0.929
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to get rid of a garnishment",
   "impr": 23,
   "clicks": 5,
   "cost": 25.27,
   "conv": 0.0,
   "top": 0.867
  },
  {
   "campaign": "S_Harassment_NW",
   "adgroup": "FDCPA_Harassment",
   "term": "fdcpa attorney",
   "impr": 23,
   "clicks": 4,
   "cost": 39.56,
   "conv": 1.0
  },
  {
   "campaign": "S_Harassment_NW",
   "adgroup": "FDCPA_Harassment",
   "term": "how to sue debt collectors for fdcpa violations",
   "impr": 23,
   "clicks": 4,
   "cost": 25.88,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "credit card debt lawyers near me",
   "impr": 23,
   "clicks": 2,
   "cost": 16.49,
   "conv": 0.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Branded",
   "term": "cavalry spv",
   "impr": 23,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "attorneys for debt collection",
   "impr": 22,
   "clicks": 2,
   "cost": 30.62,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "collection lawyer",
   "impr": 22,
   "clicks": 1,
   "cost": 10.83,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to file a response to a summons",
   "impr": 22,
   "clicks": 1,
   "cost": 5.82,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "midland credit management garnishment",
   "impr": 22,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.857
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection attorneys",
   "impr": 22,
   "clicks": 2,
   "cost": 28.79,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection lawsuit",
   "impr": 22,
   "clicks": 1,
   "cost": 2.55,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how do i stop wage garnishment",
   "impr": 22,
   "clicks": 6,
   "cost": 30.66,
   "conv": 0.33,
   "top": 0.933
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment in va",
   "impr": 22,
   "clicks": 2,
   "cost": 19.52,
   "conv": 0.67,
   "top": 0.643
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector lawyers near me",
   "impr": 21,
   "clicks": 4,
   "cost": 42.13,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt settlement lawyers near me",
   "impr": 21,
   "clicks": 2,
   "cost": 25.16,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to deal with debt collectors",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to dispute debt collection",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to settle a debt collection lawsuit",
   "impr": 21,
   "clicks": 1,
   "cost": 14.22,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnished wages",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.5
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how can i stop a garnishment",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "lawyer for wage garnishment",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.778
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "wage garnishments",
   "impr": 21,
   "clicks": 1,
   "cost": 2.52,
   "conv": 0.0,
   "top": 0.8
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "what is creditor garnishment",
   "impr": 21,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.375
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collector attorney near me",
   "impr": 21,
   "clicks": 3,
   "cost": 36.29,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "garnishment attorneys",
   "impr": 21,
   "clicks": 4,
   "cost": 60.42,
   "conv": 1.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can i stop a wage garnishment",
   "impr": 21,
   "clicks": 4,
   "cost": 33.14,
   "conv": 0.0,
   "top": 0.923
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how can you stop a garnishment",
   "impr": 21,
   "clicks": 3,
   "cost": 17.08,
   "conv": 0.0,
   "top": 0.875
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to dispute a garnishment",
   "impr": 21,
   "clicks": 2,
   "cost": 21.62,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_Harassment_NW",
   "adgroup": "Creditor_Harassment",
   "term": "debt collector harassment",
   "impr": 21,
   "clicks": 3,
   "cost": 9.4,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "15usc1692",
   "impr": 20,
   "clicks": 2,
   "cost": 11.48,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "cheap debt lawyers near me",
   "impr": 20,
   "clicks": 3,
   "cost": 65.3,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collections lawyer",
   "impr": 20,
   "clicks": 1,
   "cost": 12.65,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "i am being sued by a debt collector",
   "impr": 20,
   "clicks": 2,
   "cost": 27.51,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "i am being sued by a debt collector what do i do",
   "impr": 20,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "my debt lawyer",
   "impr": 20,
   "clicks": 3,
   "cost": 59.9,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "attorney for garnishment of wages",
   "impr": 20,
   "clicks": 4,
   "cost": 46.25,
   "conv": 0.0,
   "top": 0.909
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "loan lawyer",
   "impr": 20,
   "clicks": 1,
   "cost": 5.14,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "mandarich law group chicago",
   "impr": 20,
   "clicks": 1,
   "cost": 18.38,
   "conv": 0.0
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to get out of a garnishment",
   "impr": 20,
   "clicks": 3,
   "cost": 16.54,
   "conv": 0.0,
   "top": 0.923
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "how to stop a garnishment that has already started",
   "impr": 20,
   "clicks": 3,
   "cost": 15.94,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "lawyer for wage garnishment",
   "impr": 20,
   "clicks": 1,
   "cost": 5.13,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_Garnishment_NW",
   "adgroup": "Garnishment",
   "term": "who to contact about wage garnishment",
   "impr": 20,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.786
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "attorney for credit card lawsuit",
   "impr": 20,
   "clicks": 2,
   "cost": 37.94,
   "conv": 1.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "court summons for credit card debt",
   "impr": 20,
   "clicks": 3,
   "cost": 19.19,
   "conv": 1.0
  },
  {
   "campaign": "S_CreditCard_NW",
   "adgroup": "CC_Lawsuit",
   "term": "how to get a credit card lawsuit dismissed online",
   "impr": 20,
   "clicks": 2,
   "cost": 10.01,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "collection attorneys",
   "impr": 19,
   "clicks": 1,
   "cost": 16.95,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "consumer debt lawyers near me",
   "impr": 19,
   "clicks": 3,
   "cost": 40.54,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector lawsuit",
   "impr": 19,
   "clicks": 1,
   "cost": 6.59,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt collector lawyers",
   "impr": 19,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "fdcpa laws",
   "impr": 19,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "im being sued by a debt collector",
   "impr": 19,
   "clicks": 3,
   "cost": 13.87,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyers for debt collectors",
   "impr": 19,
   "clicks": 2,
   "cost": 16.16,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "what to do if you are being sued by a debt collector",
   "impr": 19,
   "clicks": 3,
   "cost": 9.25,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "i received a summons from a debt collector",
   "impr": 19,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop garnishment immediately",
   "impr": 19,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "judgement lawyers",
   "impr": 19,
   "clicks": 3,
   "cost": 30.25,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt consolidation lawyer",
   "impr": 18,
   "clicks": 1,
   "cost": 12.53,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt negotiation attorney",
   "impr": 18,
   "clicks": 1,
   "cost": 13.25,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to file a response to a debt lawsuit",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyers for debt collection lawsuit",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lvnv lawsuit",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "court summons for debt",
   "impr": 18,
   "clicks": 2,
   "cost": 8.45,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to respond to a lawsuit from a debt collector",
   "impr": 18,
   "clicks": 2,
   "cost": 12.64,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "lvnv funding llc garnishment",
   "impr": 18,
   "clicks": 2,
   "cost": 11.58,
   "conv": 0.0,
   "top": 0.75
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "what is garnishment",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.583
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collections lawyer near me",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "fitzgerald & associates pc jersey city",
   "impr": 18,
   "clicks": 3,
   "cost": 66.27,
   "conv": 1.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "zeus creditor defense law",
   "impr": 18,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "attorney for debt collection lawsuit near me",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt consolidation attorney",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to dispute collections",
   "impr": 17,
   "clicks": 1,
   "cost": 8.93,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to fight a debt collector in court",
   "impr": 17,
   "clicks": 1,
   "cost": 1.02,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyer for collections",
   "impr": 17,
   "clicks": 5,
   "cost": 49.98,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyer for debt",
   "impr": 17,
   "clicks": 1,
   "cost": 14.68,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "statute of limitations on debt",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "velocity investments llc suing me",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Creditor_Suing",
   "term": "portfolio recovery associates lawsuit",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Served_Papers",
   "term": "how to answer a summons",
   "impr": 17,
   "clicks": 1,
   "cost": 3.87,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "can a creditor garnish my wages after 7 years",
   "impr": 17,
   "clicks": 3,
   "cost": 11.39,
   "conv": 1.0,
   "top": 0.818
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnish creditor",
   "impr": 17,
   "clicks": 1,
   "cost": 1.48,
   "conv": 0.0,
   "top": 0.833
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how can i stop garnishment of my paycheck online",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.9
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how do i stop a garnishment",
   "impr": 17,
   "clicks": 2,
   "cost": 7.09,
   "conv": 0.0,
   "top": 0.9
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "lawyer for garnishment of wages",
   "impr": 17,
   "clicks": 2,
   "cost": 37.14,
   "conv": 2.0,
   "top": 0.889
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "collection lawyer",
   "impr": 17,
   "clicks": 2,
   "cost": 11.35,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt attorneys",
   "impr": 17,
   "clicks": 1,
   "cost": 12.69,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "how to dispute collections",
   "impr": 17,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "attorneys that deal with debt collectors",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "being sued by capital one",
   "impr": 16,
   "clicks": 1,
   "cost": 1.63,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "can a collection agency sue you",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "consumer debt defense attorney near me",
   "impr": 16,
   "clicks": 1,
   "cost": 8.12,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "debt claim citation answer sample",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "getting sued by debt collector",
   "impr": 16,
   "clicks": 3,
   "cost": 28.7,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "how to fight debt collectors in court and win",
   "impr": 16,
   "clicks": 4,
   "cost": 21.13,
   "conv": 1.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "im being sued by a debt collector what do i do",
   "impr": 16,
   "clicks": 2,
   "cost": 23.45,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "jefferson capital systems lawsuit",
   "impr": 16,
   "clicks": 1,
   "cost": 7.52,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "lawyer for being sued by debt collector",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_Lawsuit_NW",
   "adgroup": "Collection_Lawsuit",
   "term": "new start legal",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "can garnishments be stopped",
   "impr": 16,
   "clicks": 2,
   "cost": 8.36,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "garnishment order",
   "impr": 16,
   "clicks": 1,
   "cost": 2.38,
   "conv": 0.0,
   "top": 0.727
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to get out of a garnishment",
   "impr": 16,
   "clicks": 1,
   "cost": 1.19,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt defense attorney",
   "impr": 16,
   "clicks": 1,
   "cost": 5.1,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "what happens if a debt collector sues you and you have no money",
   "impr": 16,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "attorney for wage garnishment",
   "impr": 15,
   "clicks": 1,
   "cost": 15.44,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "bank garnishment",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.4
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "claim of exemption and request for hearing",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.6
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "how to stop garnishments",
   "impr": 15,
   "clicks": 1,
   "cost": 4.7,
   "conv": 0.0,
   "top": 1
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Garnishment",
   "term": "what to do if your wages are garnished",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0,
   "top": 0.7
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "attorney for debt collection lawsuit near me",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "best debt collection defense attorney near me",
   "impr": 15,
   "clicks": 2,
   "cost": 16.53,
   "conv": 1.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "consumer debt defense attorney near me",
   "impr": 15,
   "clicks": 2,
   "cost": 14.66,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "debt collection harassment attorney",
   "impr": 15,
   "clicks": 4,
   "cost": 37.15,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "griffin and associates debt collector",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "Debt Collector",
   "term": "how to answer a court summons debt collection",
   "impr": 15,
   "clicks": 1,
   "cost": 2.66,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "fdcpa laws",
   "impr": 15,
   "clicks": 0,
   "cost": 0.0,
   "conv": 0.0
  },
  {
   "campaign": "S_All-States",
   "adgroup": "FDCPA",
   "term": "fdcpa section 809",
   "impr": 15,
   "clicks": 1,
   "cost": 1.76,
   "conv": 0.0
  }
 ]
};
